In [2]:
import pandas as pd

# Load the data
hr_data_path = 'D:\\Afame\\HR Data.csv'  # Update with your file path
hr_df = pd.read_csv(hr_data_path)

# Display the first few rows of the HR data
print("Original Data:")
print(hr_df.head())

# 1. Remove unnecessary columns (example: 'EmployeeNumber' and 'StandardHours')
columns_to_remove = ['EmployeeNumber', 'StandardHours']
hr_df = hr_df.drop(columns=columns_to_remove)

# 2. Rename columns (example: 'Attrition' to 'Turnover')
columns_rename = {
    'Attrition': 'Turnover',
    'JobRole': 'Position',
    'MonthlyIncome': 'Monthly_Salary'
}
hr_df = hr_df.rename(columns=columns_rename)

# 3. Eliminate redundant entries (remove duplicates)
hr_df = hr_df.drop_duplicates()

# 4. Sanitize specific columns (example: strip whitespace from strings)
string_columns = hr_df.select_dtypes(include=['object']).columns
for col in string_columns:
    hr_df[col] = hr_df[col].str.strip()

# 5. Eliminate NaN values
hr_df = hr_df.dropna()

# 6. Check for additional necessary changes
# Example: Converting 'Age' to categorical data
hr_df['Age_Group'] = pd.cut(hr_df['Age'], bins=[18, 25, 35, 45, 55, 65], labels=['18-25', '26-35', '36-45', '46-55', '56-65'])

# Display the cleaned data
print("Cleaned Data:")
print(hr_df.head())

# Save the cleaned data to a new CSV file in the current directory
cleaned_data_path = 'Cleaned_HR_Data.csv'
hr_df.to_csv(cleaned_data_path, index=False)
print(f"Cleaned data saved to {cleaned_data_path}")

Original Data:
   Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales
1   49        No  Travel_Frequently        279  Research & Development
2   37       Yes      Travel_Rarely       1373  Research & Development
3   33        No  Travel_Frequently       1392  Research & Development
4   27        No      Travel_Rarely        591  Research & Development

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1
1                 8          1  Life Sciences              1               2
2                 2          2          Other              1               4
3                 3          4  Life Sciences              1               5
4                 2          1        Medical              1               7

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0
1  ...                         4            80                 1
2  ...                         2            80                 0
3  ...                         3            80                 0
4  ...                         4            80                 1

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6
1                 10                      3               3              10
2                  7                      3               3               0
3                  8                      3               3               8
4                  6                      3               3               2

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager
0                  4                        0                     5
1                  7                        1                     7
2                  0                        0                     0
3                  7                        3                     0
4                  2                        2                     2

[5 rows x 35 columns]
Cleaned Data:
   Age Turnover     BusinessTravel  DailyRate              Department  \
0   41      Yes      Travel_Rarely       1102                   Sales
1   49       No  Travel_Frequently        279  Research & Development
2   37      Yes      Travel_Rarely       1373  Research & Development
3   33       No  Travel_Frequently       1392  Research & Development
4   27       No      Travel_Rarely        591  Research & Development

   DistanceFromHome  Education EducationField  EmployeeCount  \
0                 1          2  Life Sciences              1
1                 8          1  Life Sciences              1
2                 2          2          Other              1
3                 3          4  Life Sciences              1
4                 2          1        Medical              1

   EnvironmentSatisfaction  ... RelationshipSatisfaction  StockOptionLevel  \
0                        2  ...                        1                 0
1                        3  ...                        4                 1
2                        4  ...                        2                 0
3                        4  ...                        3                 0
4                        1  ...                        4                 1

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6
1                 10                      3               3              10
2                  7                      3               3               0
3                  8                      3               3               8
4                  6                      3               3               2

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  Age_Group
0                  4                        0                     5      36-45
1                  7                        1                     7      46-55
2                  0                        0                     0      36-45
3                  7                        3                     0      26-35
4                  2                        2                     2      26-35

[5 rows x 34 columns]
Cleaned data saved to Cleaned_HR_Data.csv